flowchart LR
    subgraph Legend [Сценарий 1: Заполнение/обновление]
    end

    Ext[Внешний класс] -->|"запрос на заполнение/обновление"| DH[DataHandler]

    DH -->|"запрос сырых данных"| DG[DataGetter]
    DG -->|"сырые данные + DataGetter execution code"| DH

    DH -->|"передача сырых данных"| DP[DataParser]
    DP -->|"обработанные данные + DataParser execution code"| DH

    DH -->|"передача обработанных данных"| SV[Saver]
    SV -->|"сохранение"| JS[(jsonstore)]
    SV -->|"Saver execution code"| DH

    DH -->|"Datahandler execution code"| Ext